### ISSUE TITLE
Easy to reachout winner blogs

### ISSUE THREAD

**Issue by Malavi1** [thecocode/blog-a-thon#10]
### In addition to just the name of the  it would be super cool and easy to reach the winners blogs if we add the hash node links of their blogs.
![cocode](https://user-images.githubusercontent.com/112646623/230549815-50f5d1bc-d831-4326-a9d3-ba6352731929.png)

**Comment by poojasanwal** [comment]
Hey @Malavi1 
Thanks for your suggestion but most participants write more than one blog and that too for multiple tracks which are just as good. Secondly, we put the hashnode profile link so that people can easily follow them and reach out to their socials if needed. However, I will keep your suggestion in mind and think about putting the blog links for the April contest.

**Comment by Malavi1** [comment]
Thank you for the kind words!! yeah, It's cool that your mentioning their hashnode profile pages but it is having some sort of uncertainty for which they they won the track.
